
#networks:
#  nexus_network:
#    external: true

services:

# ========================================
# My POC Example  Service
# ========================================
  va-poc-service:
    image: joe-fraser-va-poc-service:1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
#appData volume is mounted inside the service at
    volumes:
#binds the local directory or file (can be relative or absolute) to the path to use in the container
     - C:\data\SQLite\va.db:/data/SQLite/va.db # Bind mount
    environment:
      - JVM_OPTS=-Xms4G -Xmx10G -Dspring.profiles.active=dev
#    networks:
#      - nexus_network
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    extra_hosts:
      - "host.docker.internal:host-gateway"
