
#networks:
#  nexus_network:
#    external: true

services:

# ========================================
# My POC Example  Service
# ========================================
  va-poc-service:
    image: joe-fraser-va-poc-service:1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
#joeFraserDataSQLite volume is mounted inside the service container at
    volumes:
#binds the external Volume to the path to use in the container
     - joeFraserDataSQLite:/data/SQLite # Bind mount
    environment:
      - JVM_OPTS=-Xms4G -Xmx10G -Dspring.profiles.active=dev
#    networks:
#      - nexus_network
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  joeFraserDataSQLite:
    external: true
